### ISSUE TITLE
Mi 8, Fail to run action returns error code 7001, with ussd dialog

### ISSUE THREAD

**Issue by Ab3id** [UseHover/SDK-Issues#32] opened 2020-04-08 09:44 UTC
![WhatsApp Image 2020-04-07 at 1 55 15 PM](https://user-images.githubusercontent.com/40204062/78769925-9def9180-7996-11ea-9b54-8f1f459a7551.jpeg)

**Comment by Yankande** [comment] 2020-04-25 06:29
assurez-vous d'avoir activer votre connexion

**Comment by davkutalek** [comment] 2020-05-01 16:55
Network issue can mean a lot of different things, but some USSD systems are just very unstable. Even if you have a good internet/voice connection some USSD systems are easily overwhelmed or buggy, so they can stop responding.

**Comment by davkutalek** [comment] 2020-07-03 14:11
Likely duplicate of https://github.com/UseHover/SDK-Issues/issues/8 restarting the device should fix it

**Closed as completed** 2020-07-03 14:10 UTC
